name: Lighthouse CI
on:
  push:
    branches: [ gh-pages ]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://rafcik.github.io/GithubActions/
          uploadArtifacts: true
          runs: 3
