# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run nx -- lint github-actions

#      - name: SonarCloud Scan
#        uses: SonarSource/sonarcloud-github-action@v1.2
#        env:
#          GITHUB_TOKEN: ${{ secrets.SONAR_GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build project
        run: npm run ng -- build github-actions --prod --base-href=/GithubActions/

      - name: Run affected tests
        run: npm run nx -- test github-actions --ci --runInBand

      - name: Run affected e2e
        run: npm run nx -- e2e github-actions-e2e --headless

      - name: Deploy to Github Pages
        if: ${{ github.ref == 'refs/heads/master' }}
        run: npm run ng -- deploy --no-build --name="rafcik" --email="GithubActions@example.com" --no-silent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lighthouse:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://rafcik.github.io/GithubActions/
          uploadArtifacts: true
          runs: 3
